spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rest_with_springboot?useTimezone=true&serverTimezone=UTC
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      format_sql: true
    database: postgresql
